export const DUMMY_CHANNELS = [
  { id: 'cam_01', name: '정문 CCTV', url: '', status: 'ok', options: [] },
  { id: 'cam_02', name: '공장 내부 A', url: '', status: 'ok', options: [] },
  { id: 'cam_03', name: '주차장', url: '', status: 'ok', options: [] },
]

export const DUMMY_EVENTS = [
  {
    id: 'evt_01',
    channel_id: 'cam_01',
    channel_name: '정문 CCTV',
    created_at: '2025-04-21T14:32:04',
    event_type: '안전복장 미착용',
    danger_level: 'high',
    reason: '작업자가 안전모를 착용하지 않고 공장 출입구를 통과하는 장면이 감지되었습니다.',
    confidence: 0.94,
    pose_event: '안전모 미착용',
    vlm_confidence: 0.91,
    thumbnail_url: null,
    clip_url: null,
  },
  {
    id: 'evt_02',
    channel_id: 'cam_02',
    channel_name: '공장 내부 A',
    created_at: '2025-04-20T09:14:00',
    event_type: '안전복장 미착용',
    danger_level: 'medium',
    reason: '작업자 2명이 안전조끼 없이 적재 구역에 접근하는 상황이 탐지되었습니다.',
    confidence: 0.82,
    pose_event: '안전조끼 미착용',
    vlm_confidence: 0.78,
    thumbnail_url: null,
    clip_url: null,
  },
  {
    id: 'evt_03',
    channel_id: 'cam_03',
    channel_name: '주차장',
    created_at: '2025-04-19T23:47:00',
    event_type: '침입',
    danger_level: 'high',
    reason: '야간 시간대 허가되지 않은 인원이 주차장 후문을 통해 진입하는 장면입니다.',
    confidence: 0.91,
    pose_event: null,
    vlm_confidence: 0.89,
    thumbnail_url: null,
    clip_url: null,
  },
]
