services:
  ingestion_0:
    volumes:
      - ./../frames:/frames
  ingestion_1:
    volumes:
      - ./../frames:/frames
  ingestion_2:
    volumes:
      - ./../frames:/frames
  ingestion_3:
    volumes:
      - ./../frames:/frames
  inference:
    volumes:
      - ./../frames:/frames
    environment:
      ANNOTATE_FRAMES: "true"