webrtcAddress: :8889
api: yes
apiAddress: :9997
authInternalUsers:
  - user: any
    pass: ""
    permissions:
      - action: api
      - action: read
      - action: publish
      - action: playback